In [209]:
# import Numpy library
import numpy as np

In [210]:
np.__version__

'1.19.2'

# NUMPY - Numerical Python


In [211]:
## Numpy- it  is one of the useful library of python. it's help to perform mathematical and logical operation with the help of array.
##  Array- it is collection of elements. 
## Matrix -it is collection of array . mostly use 2D or 3D array in matrix
## 3D Matrix-  it is collection of 2d matrices.

#  Array


In [212]:
## 1D array - one dimensional array contain only a row axis=0
## 2D array - 2 dimensional array contain rows axis=0 and columns axis=1
## 3D array- 3 dimensional array contain 1st no. of 2D array ,2nd rows and 3rd columns and 3D array is nothing but collection of 2D array . 
## 3D array also called Multi-Dimensional Array.

In [213]:
# 1D array
a_1=np.array([1,2,3])

In [214]:
a_1

array([1, 2, 3])

In [215]:
a_1.ndim

1

In [216]:
# 2D array
a_2=np.array([1,2,3,4,5,6]).reshape(2,3)

In [217]:
#a_2 is matrix because it created by collection of array.
a_2

array([[1, 2, 3],
       [4, 5, 6]])

In [218]:
a_2.ndim

2

In [219]:
# 3D array or Multi dimensional array
# reshape(no. of 2D array, no. of row, no. column)
a_3=np.array([1,2,5,6,8,9,]).reshape(1,3,2)

In [220]:
a_3

array([[[1, 2],
        [5, 6],
        [8, 9]]])

In [221]:
a_3.ndim

3

In [222]:
# 3D Matrix- collection of 2D matrices
m_3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

In [223]:
m_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [224]:
m_3.ndim

3

# list convert into array

In [225]:
# create a list
g=[1,12,3,4,5]

In [226]:
print(type(g))

<class 'list'>


In [227]:
# g variable type is  list 
# we can convert list into array
array_1=np.array(g)

In [228]:
array_1

array([ 1, 12,  3,  4,  5])

In [229]:
type(array_1)

numpy.ndarray

In [230]:
# and we can create array directly

array_=np.array([5,6,7,8,])

In [231]:
array_

array([5, 6, 7, 8])

In [232]:
type(array_)

numpy.ndarray

In [233]:
# how many dimensions in array
array_.ndim

1

In [234]:
# how many elements in array's row and column
array_.shape

(4,)

In [235]:
# total elements in array
array_.size

4

In [236]:
# create two dimensions array
arr1= np.array([[5,6,7,8,9,7,16,18,5]])

In [237]:
arr1.ndim
# 1 row and 1 column

2

In [238]:
arr1.shape
# a row with 9 columns

(1, 9)

In [239]:
arr1.size
# total elements in a array is 9

9

In [240]:
arr1

array([[ 5,  6,  7,  8,  9,  7, 16, 18,  5]])

In [241]:
arr1.dtype

dtype('int32')

# Array Manipulation

## reshape()

In [242]:
# reshape arr1 and create it on matrix
arr1=np.array(arr1).reshape(3,3)

In [243]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

In [244]:
arr1.ndim
# row and column

2

In [245]:
arr1.size
# total elements in a matrix

9

In [246]:
arr1.shape
# 3 rows and 3 columns

(3, 3)

In [247]:
# let's create another matrix 
arr2=np.array([78,55,12,13,40,50,10,20,9]).reshape(3,3)

In [248]:
arr2.ndim

2

In [249]:
arr2

array([[78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

In [250]:
arr2.shape

(3, 3)

In [251]:
# resize shape of array
arr6=arr1.copy()

In [252]:
arr6

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

## resize()

In [253]:
arr6.resize(9,1)

In [254]:
arr6

array([[ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 7],
       [16],
       [18],
       [ 5]])

## stack- joining arrays in NumPy. Arrays having same dimensions can be stacked.

In [257]:
np.stack((arr1,arr2))

array([[[ 5,  6,  7],
        [ 8,  9,  7],
        [16, 18,  5]],

       [[78, 55, 12],
        [13, 40, 50],
        [10, 20,  9]]])

##  row_stack and vstack
####Both stack work same . Both stack array in vertically(row wise).

In [258]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

In [259]:
arr2

array([[78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

In [260]:
np.row_stack((arr1,arr2))

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5],
       [78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

In [261]:
np.vstack((arr1,arr2))

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5],
       [78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

## column_stack and hstack 
####Both stack work same . Both stack array in horizontally(column wise).

In [262]:
np.column_stack((arr1,arr2))

array([[ 5,  6,  7, 78, 55, 12],
       [ 8,  9,  7, 13, 40, 50],
       [16, 18,  5, 10, 20,  9]])

In [263]:
np.hstack((arr1,arr2))

array([[ 5,  6,  7, 78, 55, 12],
       [ 8,  9,  7, 13, 40, 50],
       [16, 18,  5, 10, 20,  9]])

##  Transpose 

In [264]:
arr_5 =np.array([1,3,5,6,8,9]).reshape(1,2,3)

In [265]:
arr_5

array([[[1, 3, 5],
        [6, 8, 9]]])

In [266]:
np.transpose(arr_5)

array([[[1],
        [6]],

       [[3],
        [8]],

       [[5],
        [9]]])

In [267]:
arr1.T

array([[ 5,  8, 16],
       [ 6,  9, 18],
       [ 7,  7,  5]])

## concatenate

In [268]:
np.concatenate((arr1,arr2),axis=1)

array([[ 5,  6,  7, 78, 55, 12],
       [ 8,  9,  7, 13, 40, 50],
       [16, 18,  5, 10, 20,  9]])

In [269]:
np.concatenate((arr1,arr2),axis=0)

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5],
       [78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

## Spliting Array

In [270]:
sp_arr=np.array([1,2,3,4,5,6])

In [271]:
sp_arr

array([1, 2, 3, 4, 5, 6])

In [272]:
np.split(sp_arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [273]:
np.split(sp_arr,2)

[array([1, 2, 3]), array([4, 5, 6])]

## vsplit - vertically split array

In [274]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

In [275]:
np.vsplit(arr1,3)

[array([[5, 6, 7]]), array([[8, 9, 7]]), array([[16, 18,  5]])]

## hsplit- horizontally split array

In [276]:
np.hsplit(arr1,3)

[array([[ 5],
        [ 8],
        [16]]),
 array([[ 6],
        [ 9],
        [18]]),
 array([[7],
        [7],
        [5]])]

## Append 


In [277]:
### if the axis is not mentioned, then it  convert 2d or 3d array into 1d array
### np.append(array_name,[values],axis=0)
### dimensions according to array
### np.append(array_name,[[value],[value],[value]],axis=1)

In [278]:
np.append(arr1,[[4,8,6]],axis=0)

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5],
       [ 4,  8,  6]])

In [279]:
np.append(arr1,[[4],[7],[98]],axis=1)

array([[ 5,  6,  7,  4],
       [ 8,  9,  7,  7],
       [16, 18,  5, 98]])

In [280]:
np.append(arr1,[55,10,65])

array([ 5,  6,  7,  8,  9,  7, 16, 18,  5, 55, 10, 65])

## insert

In [281]:
### if the axis is not mentioned, then it  convert 2d or 3d array into 1d array
### np.insert(array_name,index,[values],axis=)

In [282]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

In [283]:
# insert values in column
np.insert(arr1,1,[2,5,6],axis=1)

array([[ 5,  2,  6,  7],
       [ 8,  5,  9,  7],
       [16,  6, 18,  5]])

In [284]:
np.insert(arr1,2,[5,8,9],axis=1)

array([[ 5,  6,  5,  7],
       [ 8,  9,  8,  7],
       [16, 18,  9,  5]])

In [285]:
# insert values in row
np.insert(arr1,1,[4,8,3],axis=0)

array([[ 5,  6,  7],
       [ 4,  8,  3],
       [ 8,  9,  7],
       [16, 18,  5]])

In [286]:
## let's do inserting without mention axis
np.insert(arr1,1,[8,97,5])

array([ 5,  8, 97,  5,  6,  7,  8,  9,  7, 16, 18,  5])

## Delete

In [287]:
## np.delete(array_name,position,axis=)
## if the axis is not mentioned, then it  convert 2d or 3d array into 1d array

In [288]:
np.delete(arr1,2,axis=1)

array([[ 5,  6],
       [ 8,  9],
       [16, 18]])

In [289]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

In [290]:
np.delete(arr1,0,axis=0)

array([[ 8,  9,  7],
       [16, 18,  5]])

In [291]:
np.delete(arr1,0)

array([ 6,  7,  8,  9,  7, 16, 18,  5])

In [292]:
arr_4=np.array([11,22,15,16,15,19])

In [293]:
arr_4

array([11, 22, 15, 16, 15, 19])

In [294]:
np.delete(arr_4,2)

array([11, 22, 16, 15, 19])

In [295]:
np.delete(arr_4,(0,1,2))

array([16, 15, 19])

In [296]:
np.delete(arr2,1,axis=0)

array([[78, 55, 12],
       [10, 20,  9]])

In [297]:
np.delete(arr2,(1,2),axis=0)

array([[78, 55, 12]])

In [298]:
np.delete(arr2,1,axis=1)

array([[78, 12],
       [13, 50],
       [10,  9]])

In [299]:
np.delete(arr2,(1,2),axis=1)

array([[78],
       [13],
       [10]])

# Array creation routines

In [301]:
arr2

array([[78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

## identity()

In [302]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## diag()

In [303]:
np.diag(arr2)

array([78, 40,  9])

## eye()

In [304]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

## ones()

In [305]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## zeros()

In [306]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## arange()

In [423]:
# create array with arange(start,stop,step)
a_2=np.arange(2,13,2).reshape(2,3)

In [308]:
a_2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [309]:
# other way to create array with arange is 
a_3= np.arange(6).reshape(2,3)

In [310]:
a_3

array([[0, 1, 2],
       [3, 4, 5]])

## copy()

In [311]:
a_8=a_2.copy()

In [312]:
a_8

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## full()

In [313]:
np.full((4,3),fill_value=5,dtype='bool')

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [314]:
np.full((4,4),fill_value=0,dtype='bool')

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## linspace()

In [315]:
#np.linspace(start,stop, number of element)
big_arr=np.linspace(1,10).reshape(2,25)# by default linspace show 50 no. of sample
print(big_arr)

[[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
   2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
   3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
   4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
   5.40816327]
 [ 5.59183673  5.7755102   5.95918367  6.14285714  6.32653061  6.51020408
   6.69387755  6.87755102  7.06122449  7.24489796  7.42857143  7.6122449
   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224  8.71428571
   8.89795918  9.08163265  9.26530612  9.44897959  9.63265306  9.81632653
  10.        ]]


# Arithmetic Operators in Numpy

In [316]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

In [317]:
arr2

array([[78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

In [318]:
arr1 + arr2

array([[83, 61, 19],
       [21, 49, 57],
       [26, 38, 14]])

In [319]:
arr1 - arr2

array([[-73, -49,  -5],
       [ -5, -31, -43],
       [  6,  -2,  -4]])

In [320]:
arr1* arr2

array([[390, 330,  84],
       [104, 360, 350],
       [160, 360,  45]])

In [321]:
arr1.dot(arr2) # dot product condition no. of columns of first array should be equal to no. of rows of second array

array([[ 538,  655,  423],
       [ 811,  940,  609],
       [1532, 1700, 1137]])

In [322]:
arr1/arr2

array([[0.06410256, 0.10909091, 0.58333333],
       [0.61538462, 0.225     , 0.14      ],
       [1.6       , 0.9       , 0.55555556]])

In [323]:
arr2%arr1 # % modulus show remainder

array([[ 3,  1,  5],
       [ 5,  4,  1],
       [10,  2,  4]], dtype=int32)

In [324]:
arr2//arr1 # floor division show quotient

array([[15,  9,  1],
       [ 1,  4,  7],
       [ 0,  1,  1]], dtype=int32)

# statistical aggregation

In [325]:
# add
np.add(a_1,a_2)

array([[ 3,  6,  9],
       [ 9, 12, 15]])

In [326]:
# subtract
np.subtract(a_1,a_2)

array([[-1, -2, -3],
       [-7, -8, -9]])

In [327]:
# multiplication
np.multiply(a_1,a_2)

array([[ 2,  8, 18],
       [ 8, 20, 36]])

In [328]:
# divide
np.divide(a_1,a_2)

array([[0.5  , 0.5  , 0.5  ],
       [0.125, 0.2  , 0.25 ]])

In [329]:
# let's find out the minimum no. in matrix a_1
a_1.min()

1

In [330]:
# position of minimum no. 
np.argmin(a_1)

0

In [331]:
# position of maximum no.
np.argmax(a_1)

2

In [332]:
# let's find out the maximun no. in matrix a_1
a_1.max()

3

In [333]:
# now we are going to find row which contain minimum no. in matrix a_2
a_2.min(axis=0)

array([2, 4, 6])

In [334]:
a_2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [335]:
# now we are going to find column which contain minimum no. in matrix a_2
a_2.min(axis=1)

array([2, 8])

In [336]:
# now we are going to find column which contain maximum no. in matrix a_2
a_2.max(axis=1)

array([ 6, 12])

In [337]:
# now we are going to find row which contain  maximum no. in matrix a_2
a_2.max(axis=0)

array([ 8, 10, 12])

In [338]:
d=np.array([1,2,3])

In [339]:
#square
np.square(d)

array([1, 4, 9], dtype=int32)

In [340]:
k=np.array([49,25,64])

In [341]:
k

array([49, 25, 64])

In [342]:
# square root
np.sqrt(k)

array([7., 5., 8.])

In [343]:
# display unique no. of NumPy
np.unique(arr1)

array([ 5,  6,  7,  8,  9, 16, 18])

In [344]:
np.sum(arr1)

81

In [345]:
np.cumsum(arr1)

array([ 5, 11, 18, 26, 35, 42, 58, 76, 81], dtype=int32)

In [346]:
np.sum(np.cumsum(arr1))

352

In [347]:
np.cumproduct(arr1)

array([        5,        30,       210,      1680,     15120,    105840,
         1693440,  30481920, 152409600], dtype=int32)

In [348]:
# mean
arr1.mean(axis=1)

array([ 6.,  8., 13.])

In [349]:
# median
np.median(arr1,axis=0)

array([8., 9., 7.])

# random number

In [350]:
np.random.randint(5) # it show randomly 1 interger 

2

In [351]:
np.random.randn(5)
# it show random no. on specific time which is define under open brackets
# no. between 0 to 1

array([-0.64934995, -2.12532129,  0.28343718, -0.33898109, -0.38545544])

In [352]:
# here we can define that how many rows and columns we need
np.random.rand(10,5)

array([[0.78663634, 0.23360534, 0.39529149, 0.25030083, 0.82156628],
       [0.84286148, 0.70846566, 0.57276497, 0.69232498, 0.30459291],
       [0.40595962, 0.61047041, 0.69447539, 0.96351373, 0.17722438],
       [0.89164826, 0.57132452, 0.11602856, 0.61743513, 0.03626399],
       [0.67420332, 0.83780145, 0.5827954 , 0.79558286, 0.94552843],
       [0.3352297 , 0.06854039, 0.32617024, 0.40904702, 0.60247379],
       [0.72123707, 0.1981782 , 0.051438  , 0.91202272, 0.83997805],
       [0.53630586, 0.96320111, 0.84396035, 0.05495723, 0.66929044],
       [0.8403452 , 0.41944936, 0.19573037, 0.95787457, 0.28264604],
       [0.24035529, 0.40197867, 0.4796392 , 0.10945054, 0.35142211]])

#  convert matrix into list

In [353]:
a_8=np.array([2,4,6,8,10,12]).reshape(2,3)

In [354]:
a_8

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [355]:
a_10=list(a_8)

In [356]:
a_10

[array([2, 4, 6]), array([ 8, 10, 12])]

In [357]:
type(a_10)

list

In [358]:
# other way to convert array to list
a_8.tolist()

[[2, 4, 6], [8, 10, 12]]

# condition

In [359]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

In [360]:
arr1>=7

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [361]:
arr1[arr1>=7]

array([ 7,  8,  9,  7, 16, 18])

In [362]:
arr1[(arr1 <=18 )& (arr1>=9)]

array([ 9, 16, 18])

In [363]:
condition_1=(arr1>=9) | (arr1<9)

In [364]:
arr1[condition_1]

array([ 5,  6,  7,  8,  9,  7, 16, 18,  5])

In [365]:
arr1[arr1!=9]

array([ 5,  6,  7,  8,  7, 16, 18,  5])

# where condition
np.where(condition,if,else)

In [366]:
np.where(arr1>18, arr1,arr1*10)

array([[ 50,  60,  70],
       [ 80,  90,  70],
       [160, 180,  50]])

In [367]:
arr1[np.where(arr1<=9)]

array([5, 6, 7, 8, 9, 7, 5])

In [368]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

# Indexing in NumPy

In [369]:
## indexing is the way to get value of particular position of array
## indexing is used to get an element of array and also used to get elements of row or column
## 1d array = [position number]
## 2d array= [row,column] or [row][column]
## 3d array=[array position][row][column] or [array position][row,column] or  [array position,row,column]  

In [370]:
# indexing on 1d array
a=np.array([1,2,3,5])

In [371]:
a.ndim

1

In [372]:
# get no. 5 by indexing
a[3]

5

In [373]:
a[-1]

5

In [374]:
a[1]

2

In [375]:
a[2]

3

In [376]:
## 2d array
arr2

array([[78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

In [377]:
arr2.ndim

2

In [378]:
# let's get no. 40 in matrix arr2
arr2[1,1]

40

In [379]:
# indexing is used to get an element of array
arr2[2,2]

9

In [380]:
arr2[[0,2],[0]]

array([78, 10])

In [381]:
arr2[-1,-1]

9

In [382]:
# indexing also used to get elements of row or column
arr2[-1]

array([10, 20,  9])

In [383]:
arr2

array([[78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

In [384]:
arr2[1,1]

40

In [385]:
arr2[2,2]

9

In [386]:
arr2[1][1]

40

In [387]:
## 3d array
arr_5=np.array([1,3,5,6,8,9]).reshape(1,2,3)

In [388]:
arr_5.ndim

3

In [389]:
arr_5

array([[[1, 3, 5],
        [6, 8, 9]]])

In [390]:
# get value 9 from 3d array arr_5
arr_5[0][1,2]

9

In [391]:
arr_5[0][1][2]

9

In [392]:
arr_5[0,1,2]

9

In [393]:
## above we shown that there is more than 1 way to get indexing of 3d array

In [394]:
arr_5[0][1][0]

6

In [395]:
arr_5[0][0][-1]

5

# Slicing in NumPy

In [396]:
# slicing means getting a subset of elements from  array .
# 1d array = [start:stop:step] or [start:stop]
# 2d array= [row's start:stop ,  column's  start:stop]
# 3d array=[array position] [row's start:stop ,  column's  start:stop]   or  [array position,row's start:stop ,  column's  start:stop]  

In [397]:
# first we are going to work on 1d array
a

array([1, 2, 3, 5])

In [398]:
a[0:3:1] # [start:stop:stepping]

array([1, 2, 3])

In [399]:
# we want value from 1 to 3
a[0:3]

array([1, 2, 3])

In [400]:
a[1:4]

array([2, 3, 5])

In [401]:
a[-1:-1]

array([], dtype=int32)

In [402]:
a[2:4]

array([3, 5])

In [403]:
# now we are working on 2d array 
arr2

array([[78, 55, 12],
       [13, 40, 50],
       [10, 20,  9]])

In [404]:
arr2[0:3,0]

array([78, 13, 10])

In [405]:
arr2[1:3,1]

array([40, 20])

In [406]:
# we want to extract the value 78 55
#                              13 40 from array arr2
arr2[0:2,0:2]

array([[78, 55],
       [13, 40]])

In [407]:
# let's extract value [40 50
#                     20 90] from array arr2

arr2[1:3,1:3]

array([[40, 50],
       [20,  9]])

In [408]:
arr2[0:2]

array([[78, 55, 12],
       [13, 40, 50]])

In [409]:
arr2[1:3,0:2]

array([[13, 40],
       [10, 20]])

In [410]:
## here we are going to do slicing on 3d array
arr_5

array([[[1, 3, 5],
        [6, 8, 9]]])

In [411]:
arr_5[0][0:2,0]

array([1, 6])

In [412]:
arr_5[0,0:2,0]

array([1, 6])

In [413]:
arr_5[0,0:2,1]

array([3, 8])

In [414]:
arr_5[0][0:2,1]

array([3, 8])

#  converting data type of existing arrays

In [415]:
arr1

array([[ 5,  6,  7],
       [ 8,  9,  7],
       [16, 18,  5]])

In [416]:
arr1.dtype

dtype('int32')

In [417]:
i=arr1.astype('float')

In [418]:
i.dtype

dtype('float64')

In [419]:
i

array([[ 5.,  6.,  7.],
       [ 8.,  9.,  7.],
       [16., 18.,  5.]])

In [420]:
b=arr1.astype('bool')

In [421]:
b.dtype

dtype('bool')

In [422]:
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])